"""New migration.

Revision ID: 24b164081b4d
Revises: 5c27d6c3634e
Create Date: 2023-10-19 08:48:10.235771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24b164081b4d'
down_revision = '5c27d6c3634e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointment',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('duration', sa.String(length=10), nullable=False),
    sa.Column('clinician', sa.String(length=255), nullable=False),
    sa.Column('department', sa.String(length=255), nullable=False),
    sa.Column('postcode', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patient',
    sa.Column('nhs_number', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('postcode', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('nhs_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patient')
    op.drop_table('appointment')
    # ### end Alembic commands ###
